# Generated by Django 4.2.23 on 2025-08-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('fire', 'Fire'), ('water', 'Water'), ('electric', 'Electric'), ('grass', 'Grass'), ('ice', 'Ice'), ('fighting', 'Fighting'), ('poison', 'Poison'), ('ground', 'Ground'), ('flying', 'Flying'), ('psychic', 'Psychic'), ('bug', 'Bug'), ('rock', 'Rock'), ('ghost', 'Ghost'), ('dragon', 'Dragon'), ('dark', 'Dark'), ('steel', 'Steel'), ('fairy', 'Fairy')], max_length=20)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('effect', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('physical', 'Physical'), ('special', 'Special'), ('status', 'Status')], max_length=20)),
                ('accuracy', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sprite', models.URLField(blank=True, null=True)),
                ('type_1', models.CharField(max_length=50)),
                ('type_2', models.CharField(blank=True, max_length=50, null=True)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('sp_atk', models.IntegerField()),
                ('sp_def', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
        ),
    ]
