# Generated by Django 4.2.23 on 2025-08-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=models.ManyToManyField(blank=True, related_name='pokemon', to='pokemon.move'),
        ),
    ]
