# Generated by Django 4.2.23 on 2025-08-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_pokemon_moves'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
