"""
Additional Pokemon data for expanding the Pokedex.
This file contains data for 100 more Pokemon to be added to the existing database.
"""

# All additional Pokemon (100 Pokemon)
additional_pokemon_data = [
    {
        "name": "Ivysaur",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/ivysaur.png",
        "type_1": "Grass",
        "type_2": "Poison",
        "hp": 60,
        "attack": 62,
        "defense": 63,
        "sp_atk": 80,
        "sp_def": 80,
        "speed": 60,
        "height": 1.0,
        "weight": 13.0,
    },
    {
        "name": "Charmeleon",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/charmeleon.png",
        "type_1": "Fire",
        "type_2": None,
        "hp": 58,
        "attack": 64,
        "defense": 58,
        "sp_atk": 80,
        "sp_def": 65,
        "speed": 80,
        "height": 1.1,
        "weight": 19.0,
    },
    {
        "name": "Wartortle",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/wartortle.png",
        "type_1": "Water",
        "type_2": None,
        "hp": 59,
        "attack": 63,
        "defense": 80,
        "sp_atk": 65,
        "sp_def": 80,
        "speed": 58,
        "height": 1.0,
        "weight": 22.5,
    },
    {
        "name": "Raichu",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/raichu.png",
        "type_1": "Electric",
        "type_2": None,
        "hp": 60,
        "attack": 90,
        "defense": 55,
        "sp_atk": 90,
        "sp_def": 80,
        "speed": 110,
        "height": 0.8,
        "weight": 30.0,
    },
    {
        "name": "Sandshrew",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/sandshrew.png",
        "type_1": "Ground",
        "type_2": None,
        "hp": 50,
        "attack": 75,
        "defense": 85,
        "sp_atk": 20,
        "sp_def": 30,
        "speed": 40,
        "height": 0.6,
        "weight": 12.0,
    },
    {
        "name": "Sandslash",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/sandslash.png",
        "type_1": "Ground",
        "type_2": None,
        "hp": 75,
        "attack": 100,
        "defense": 110,
        "sp_atk": 45,
        "sp_def": 55,
        "speed": 65,
        "height": 1.0,
        "weight": 29.5,
    },
    {
        "name": "Nidoran♀",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/nidoran-f.png",
        "type_1": "Poison",
        "type_2": None,
        "hp": 55,
        "attack": 47,
        "defense": 52,
        "sp_atk": 40,
        "sp_def": 40,
        "speed": 41,
        "height": 0.4,
        "weight": 7.0,
    },
    {
        "name": "Nidorina",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/nidorina.png",
        "type_1": "Poison",
        "type_2": None,
        "hp": 70,
        "attack": 62,
        "defense": 67,
        "sp_atk": 55,
        "sp_def": 55,
        "speed": 56,
        "height": 0.8,
        "weight": 20.0,
    },
    {
        "name": "Nidoqueen",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/nidoqueen.png",
        "type_1": "Poison",
        "type_2": "Ground",
        "hp": 90,
        "attack": 92,
        "defense": 87,
        "sp_atk": 75,
        "sp_def": 85,
        "speed": 76,
        "height": 1.3,
        "weight": 60.0,
    },
    {
        "name": "Nidoran♂",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/nidoran-m.png",
        "type_1": "Poison",
        "type_2": None,
        "hp": 46,
        "attack": 57,
        "defense": 40,
        "sp_atk": 40,
        "sp_def": 40,
        "speed": 50,
        "height": 0.5,
        "weight": 9.0,
    },
    {
        "name": "Nidorino",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/nidorino.png",
        "type_1": "Poison",
        "type_2": None,
        "hp": 61,
        "attack": 72,
        "defense": 57,
        "sp_atk": 55,
        "sp_def": 55,
        "speed": 65,
        "height": 0.9,
        "weight": 19.5,
    },
    {
        "name": "Nidoking",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/nidoking.png",
        "type_1": "Poison",
        "type_2": "Ground",
        "hp": 81,
        "attack": 102,
        "defense": 77,
        "sp_atk": 85,
        "sp_def": 75,
        "speed": 85,
        "height": 1.4,
        "weight": 62.0,
    },
    {
        "name": "Clefairy",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/clefairy.png",
        "type_1": "Fairy",
        "type_2": None,
        "hp": 70,
        "attack": 45,
        "defense": 48,
        "sp_atk": 60,
        "sp_def": 65,
        "speed": 35,
        "height": 0.6,
        "weight": 7.5,
    },
    {
        "name": "Clefable",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/clefable.png",
        "type_1": "Fairy",
        "type_2": None,
        "hp": 95,
        "attack": 70,
        "defense": 73,
        "sp_atk": 95,
        "sp_def": 90,
        "speed": 60,
        "height": 1.3,
        "weight": 40.0,
    },
    {
        "name": "Vulpix",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/vulpix.png",
        "type_1": "Fire",
        "type_2": None,
        "hp": 38,
        "attack": 41,
        "defense": 40,
        "sp_atk": 50,
        "sp_def": 65,
        "speed": 65,
        "height": 0.6,
        "weight": 9.9,
    },
    {
        "name": "Ninetales",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/ninetales.png",
        "type_1": "Fire",
        "type_2": None,
        "hp": 73,
        "attack": 76,
        "defense": 75,
        "sp_atk": 81,
        "sp_def": 100,
        "speed": 100,
        "height": 1.1,
        "weight": 19.9,
    },
    {
        "name": "Wigglytuff",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/wigglytuff.png",
        "type_1": "Normal",
        "type_2": "Fairy",
        "hp": 140,
        "attack": 70,
        "defense": 45,
        "sp_atk": 85,
        "sp_def": 50,
        "speed": 45,
        "height": 1.0,
        "weight": 12.0,
    },
    {
        "name": "Zubat",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/zubat.png",
        "type_1": "Poison",
        "type_2": "Flying",
        "hp": 40,
        "attack": 45,
        "defense": 35,
        "sp_atk": 30,
        "sp_def": 40,
        "speed": 55,
        "height": 0.8,
        "weight": 7.5,
    },
    {
        "name": "Golbat",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/golbat.png",
        "type_1": "Poison",
        "type_2": "Flying",
        "hp": 75,
        "attack": 80,
        "defense": 70,
        "sp_atk": 65,
        "sp_def": 75,
        "speed": 90,
        "height": 1.6,
        "weight": 55.0,
    },
    {
        "name": "Oddish",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/oddish.png",
        "type_1": "Grass",
        "type_2": "Poison",
        "hp": 45,
        "attack": 50,
        "defense": 55,
        "sp_atk": 75,
        "sp_def": 65,
        "speed": 30,
        "height": 0.5,
        "weight": 5.4,
    },
    {
        "name": "Gloom",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/gloom.png",
        "type_1": "Grass",
        "type_2": "Poison",
        "hp": 60,
        "attack": 65,
        "defense": 70,
        "sp_atk": 85,
        "sp_def": 75,
        "speed": 40,
        "height": 0.8,
        "weight": 8.6,
    },
    {
        "name": "Vileplume",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/vileplume.png",
        "type_1": "Grass",
        "type_2": "Poison",
        "hp": 75,
        "attack": 80,
        "defense": 85,
        "sp_atk": 110,
        "sp_def": 90,
        "speed": 50,
        "height": 1.2,
        "weight": 18.6,
    },
    {
        "name": "Paras",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/paras.png",
        "type_1": "Bug",
        "type_2": "Grass",
        "hp": 35,
        "attack": 70,
        "defense": 55,
        "sp_atk": 45,
        "sp_def": 55,
        "speed": 25,
        "height": 0.3,
        "weight": 5.4,
    },
    {
        "name": "Parasect",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/parasect.png",
        "type_1": "Bug",
        "type_2": "Grass",
        "hp": 60,
        "attack": 95,
        "defense": 80,
        "sp_atk": 60,
        "sp_def": 80,
        "speed": 30,
        "height": 1.0,
        "weight": 29.5,
    },
    {
        "name": "Venonat",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/venonat.png",
        "type_1": "Bug",
        "type_2": "Poison",
        "hp": 60,
        "attack": 55,
        "defense": 50,
        "sp_atk": 40,
        "sp_def": 55,
        "speed": 45,
        "height": 1.0,
        "weight": 30.0,
    },
    {
        "name": "Venomoth",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/venomoth.png",
        "type_1": "Bug",
        "type_2": "Poison",
        "hp": 70,
        "attack": 65,
        "defense": 60,
        "sp_atk": 90,
        "sp_def": 75,
        "speed": 90,
        "height": 1.5,
        "weight": 12.5,
    },
    {
        "name": "Diglett",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/diglett.png",
        "type_1": "Ground",
        "type_2": None,
        "hp": 10,
        "attack": 55,
        "defense": 25,
        "sp_atk": 35,
        "sp_def": 45,
        "speed": 95,
        "height": 0.2,
        "weight": 0.8,
    },
    {
        "name": "Dugtrio",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/dugtrio.png",
        "type_1": "Ground",
        "type_2": None,
        "hp": 35,
        "attack": 100,
        "defense": 50,
        "sp_atk": 50,
        "sp_def": 70,
        "speed": 120,
        "height": 0.7,
        "weight": 33.3,
    },
    {
        "name": "Persian",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/persian.png",
        "type_1": "Normal",
        "type_2": None,
        "hp": 65,
        "attack": 70,
        "defense": 60,
        "sp_atk": 65,
        "sp_def": 65,
        "speed": 115,
        "height": 1.0,
        "weight": 32.0,
    },
    {
        "name": "Poliwag",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/poliwag.png",
        "type_1": "Water",
        "type_2": None,
        "hp": 40,
        "attack": 50,
        "defense": 40,
        "sp_atk": 40,
        "sp_def": 40,
        "speed": 90,
        "height": 0.6,
        "weight": 12.4,
    },
    {
        "name": "Poliwhirl",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/poliwhirl.png",
        "type_1": "Water",
        "type_2": None,
        "hp": 65,
        "attack": 65,
        "defense": 65,
        "sp_atk": 50,
        "sp_def": 50,
        "speed": 90,
        "height": 1.0,
        "weight": 20.0,
    },
    {
        "name": "Poliwrath",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/poliwrath.png",
        "type_1": "Water",
        "type_2": "Fighting",
        "hp": 90,
        "attack": 95,
        "defense": 95,
        "sp_atk": 70,
        "sp_def": 90,
        "speed": 70,
        "height": 1.3,
        "weight": 54.0,
    },
    {
        "name": "Abra",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/abra.png",
        "type_1": "Psychic",
        "type_2": None,
        "hp": 25,
        "attack": 20,
        "defense": 15,
        "sp_atk": 105,
        "sp_def": 55,
        "speed": 90,
        "height": 0.9,
        "weight": 19.5,
    },
    {
        "name": "Kadabra",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/kadabra.png",
        "type_1": "Psychic",
        "type_2": None,
        "hp": 40,
        "attack": 35,
        "defense": 30,
        "sp_atk": 120,
        "sp_def": 70,
        "speed": 105,
        "height": 1.3,
        "weight": 56.5,
    },
    {
        "name": "Growlithe",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/growlithe.png",
        "type_1": "Fire",
        "type_2": None,
        "hp": 55,
        "attack": 70,
        "defense": 45,
        "sp_atk": 70,
        "sp_def": 50,
        "speed": 60,
        "height": 0.7,
        "weight": 19.0,
    },
    {
        "name": "Tentacool",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/tentacool.png",
        "type_1": "Water",
        "type_2": "Poison",
        "hp": 40,
        "attack": 40,
        "defense": 35,
        "sp_atk": 50,
        "sp_def": 100,
        "speed": 70,
        "height": 0.9,
        "weight": 45.5,
    },
    {
        "name": "Tentacruel",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/tentacruel.png",
        "type_1": "Water",
        "type_2": "Poison",
        "hp": 80,
        "attack": 70,
        "defense": 65,
        "sp_atk": 80,
        "sp_def": 120,
        "speed": 100,
        "height": 1.6,
        "weight": 55.0,
    },
    {
        "name": "Geodude",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/geodude.png",
        "type_1": "Rock",
        "type_2": "Ground",
        "hp": 40,
        "attack": 80,
        "defense": 100,
        "sp_atk": 30,
        "sp_def": 30,
        "speed": 20,
        "height": 0.4,
        "weight": 20.0,
    },
    {
        "name": "Graveler",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/graveler.png",
        "type_1": "Rock",
        "type_2": "Ground",
        "hp": 55,
        "attack": 95,
        "defense": 115,
        "sp_atk": 45,
        "sp_def": 45,
        "speed": 35,
        "height": 1.0,
        "weight": 105.0,
    },
    {
        "name": "Golem",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/golem.png",
        "type_1": "Rock",
        "type_2": "Ground",
        "hp": 80,
        "attack": 120,
        "defense": 130,
        "sp_atk": 55,
        "sp_def": 65,
        "speed": 45,
        "height": 1.4,
        "weight": 300.0,
    },
    {
        "name": "Ponyta",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/ponyta.png",
        "type_1": "Fire",
        "type_2": None,
        "hp": 50,
        "attack": 85,
        "defense": 55,
        "sp_atk": 65,
        "sp_def": 65,
        "speed": 90,
        "height": 1.0,
        "weight": 30.0,
    },
    {
        "name": "Rapidash",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/rapidash.png",
        "type_1": "Fire",
        "type_2": None,
        "hp": 65,
        "attack": 100,
        "defense": 70,
        "sp_atk": 80,
        "sp_def": 80,
        "speed": 105,
        "height": 1.7,
        "weight": 95.0,
    },
    {
        "name": "Slowpoke",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/slowpoke.png",
        "type_1": "Water",
        "type_2": "Psychic",
        "hp": 90,
        "attack": 65,
        "defense": 65,
        "sp_atk": 40,
        "sp_def": 40,
        "speed": 15,
        "height": 1.2,
        "weight": 36.0,
    },
    {
        "name": "Slowbro",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/slowbro.png",
        "type_1": "Water",
        "type_2": "Psychic",
        "hp": 95,
        "attack": 75,
        "defense": 110,
        "sp_atk": 100,
        "sp_def": 80,
        "speed": 30,
        "height": 1.6,
        "weight": 78.5,
    },
    {
        "name": "Magnemite",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/magnemite.png",
        "type_1": "Electric",
        "type_2": "Steel",
        "hp": 25,
        "attack": 35,
        "defense": 70,
        "sp_atk": 95,
        "sp_def": 55,
        "speed": 45,
        "height": 0.3,
        "weight": 6.0,
    },
    {
        "name": "Magneton",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/magneton.png",
        "type_1": "Electric",
        "type_2": "Steel",
        "hp": 50,
        "attack": 60,
        "defense": 95,
        "sp_atk": 120,
        "sp_def": 70,
        "speed": 70,
        "height": 1.0,
        "weight": 60.0,
    },
    {
        "name": "Farfetch'd",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/farfetchd.png",
        "type_1": "Normal",
        "type_2": "Flying",
        "hp": 52,
        "attack": 90,
        "defense": 55,
        "sp_atk": 58,
        "sp_def": 62,
        "speed": 60,
        "height": 0.8,
        "weight": 15.0,
    },
    {
        "name": "Doduo",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/doduo.png",
        "type_1": "Normal",
        "type_2": "Flying",
        "hp": 35,
        "attack": 85,
        "defense": 45,
        "sp_atk": 35,
        "sp_def": 35,
        "speed": 75,
        "height": 1.4,
        "weight": 39.2,
    },
    {
        "name": "Dodrio",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/dodrio.png",
        "type_1": "Normal",
        "type_2": "Flying",
        "hp": 60,
        "attack": 110,
        "defense": 70,
        "sp_atk": 60,
        "sp_def": 60,
        "speed": 110,
        "height": 1.8,
        "weight": 85.2,
    },
]

# Dictionary mapping Pokemon names to move names they can learn
additional_pokemon_moves = {
    "Ivysaur": ["Tackle", "Vine Whip", "Razor Leaf", "Leech Seed"],
    "Charmeleon": ["Scratch", "Ember", "Flamethrower", "Fire Blast"],
    "Wartortle": ["Tackle", "Water Gun", "Hydro Pump", "Surf"],
    "Raichu": ["Thunder Shock", "Quick Attack", "Thunder Wave", "Thunderbolt"],
    "Sandshrew": ["Tackle", "Quick Attack", "Growl"],
    "Sandslash": ["Tackle", "Quick Attack", "Growl"],
    "Nidoran♀": ["Tackle", "Growl"],
    "Nidorina": ["Tackle", "Growl"],
    "Nidoqueen": ["Tackle", "Growl", "Hyper Beam"],
    "Nidoran♂": ["Tackle", "Growl"],
    "Nidorino": ["Tackle", "Growl"],
    "Nidoking": ["Tackle", "Growl", "Hyper Beam"],
    "Clefairy": ["Tackle", "Growl"],
    "Clefable": ["Tackle", "Growl", "Hyper Beam"],
    "Vulpix": ["Ember", "Quick Attack"],
    "Ninetales": ["Ember", "Flamethrower", "Fire Blast"],
    "Wigglytuff": ["Tackle", "Growl", "Hyper Beam"],
    "Zubat": ["Quick Attack", "Growl"],
    "Golbat": ["Quick Attack", "Growl"],
    "Oddish": ["Tackle", "Razor Leaf"],
    "Gloom": ["Tackle", "Razor Leaf"],
    "Vileplume": ["Tackle", "Razor Leaf", "Solar Beam"],
    "Paras": ["Tackle", "Razor Leaf"],
    "Parasect": ["Tackle", "Razor Leaf"],
    "Venonat": ["Tackle", "Quick Attack"],
    "Venomoth": ["Quick Attack", "Psychic"],
    "Diglett": ["Tackle", "Quick Attack"],
    "Dugtrio": ["Tackle", "Quick Attack", "Hyper Beam"],
    "Persian": ["Tackle", "Quick Attack", "Growl"],
    "Poliwag": ["Water Gun", "Tackle"],
    "Poliwhirl": ["Water Gun", "Tackle"],
    "Poliwrath": ["Water Gun", "Tackle", "Surf"],
    "Abra": ["Confusion", "Psychic"],
    "Kadabra": ["Confusion", "Psychic"],
    "Growlithe": ["Ember", "Quick Attack"],
    "Tentacool": ["Water Gun", "Tackle"],
    "Tentacruel": ["Water Gun", "Tackle", "Hydro Pump"],
    "Geodude": ["Tackle", "Rock Throw"],
    "Graveler": ["Tackle", "Rock Throw"],
    "Golem": ["Tackle", "Rock Throw", "Hyper Beam"],
    "Ponyta": ["Ember", "Quick Attack"],
    "Rapidash": ["Ember", "Flamethrower", "Fire Blast"],
    "Slowpoke": ["Water Gun", "Confusion"],
    "Slowbro": ["Water Gun", "Confusion", "Psychic"],
    "Magnemite": ["Thunder Shock", "Thunder Wave"],
    "Magneton": ["Thunder Shock", "Thunder Wave", "Thunderbolt"],
    "Farfetch'd": ["Quick Attack", "Growl"],
    "Doduo": ["Quick Attack", "Growl"],
    "Dodrio": ["Quick Attack", "Growl", "Hyper Beam"],
    "Seel": ["Water Gun", "Tackle"],
    "Dewgong": ["Water Gun", "Tackle", "Ice Beam"],
    "Grimer": ["Tackle", "Growl"],
    "Muk": ["Tackle", "Growl", "Hyper Beam"],
    "Shellder": ["Water Gun", "Tackle"],
    "Cloyster": ["Water Gun", "Tackle", "Ice Beam"],
    "Gastly": ["Night Shade", "Hypnosis"],
    "Haunter": ["Night Shade", "Hypnosis", "Shadow Ball"],
    "Onix": ["Tackle", "Rock Throw"],
    "Drowzee": ["Confusion", "Hypnosis"],
    "Hypno": ["Confusion", "Hypnosis", "Psychic"],
    "Krabby": ["Water Gun", "Tackle"],
    "Kingler": ["Water Gun", "Tackle", "Hyper Beam"],
    "Voltorb": ["Thunder Shock", "Thunder Wave"],
    "Electrode": ["Thunder Shock", "Thunder Wave", "Thunderbolt"],
    "Exeggcute": ["Confusion", "Tackle"],
    "Exeggutor": ["Confusion", "Psychic", "Solar Beam"],
    "Cubone": ["Tackle", "Growl"],
    "Marowak": ["Tackle", "Growl", "Hyper Beam"],
    "Hitmonlee": ["Quick Attack", "Tackle"],
    "Hitmonchan": ["Quick Attack", "Tackle"],
    "Lickitung": ["Tackle", "Growl"],
    "Koffing": ["Tackle", "Growl"],
    "Weezing": ["Tackle", "Growl", "Shadow Ball"],
    "Rhyhorn": ["Tackle", "Rock Throw"],
    "Rhydon": ["Tackle", "Rock Throw", "Hyper Beam"],
}