"""
Pokemon data for the Pokedex application.
This file contains all Pokemon data and their move mappings.
"""

# Dictionary mapping Pokemon names to move names they can learn
pokemon_moves = {
    "Pikachu": ["Thunder Shock", "Quick Attack", "Thunder Wave", "Thunderbolt"],
    "Bulbasaur": ["Tackle", "Vine Whip", "Razor Leaf", "Leech Seed"],
    "Charmander": ["Scratch", "Ember", "Flamethrower", "Fire Blast"],
    "Squirtle": ["Tackle", "Water Gun", "Hydro Pump", "Surf"],
    "Jigglypuff": ["Tackle", "Growl", "Hyper Beam"],
    "Meowth": ["Tackle", "Quick Attack", "Growl"],
    "Psyduck": ["Water Gun", "Confusion", "Psychic"],
    "Gengar": ["Shadow Ball", "Night Shade", "Hypnosis"],
    "Eevee": ["Tackle", "Quick Attack", "Growl"],
    "Snorlax": ["Tackle", "Hyper Beam"],
    "Mewtwo": ["Confusion", "Psychic", "Shadow Ball"],
    "Gyarados": ["Hydro Pump", "Surf", "Hyper Beam"],
    "Dragonite": ["Hyper Beam", "Thunder", "Fire Blast"],
    "Charizard": ["Ember", "Flamethrower", "Fire Blast"],
    "Blastoise": ["Water Gun", "Hydro Pump", "Surf"],
    "Venusaur": ["Vine Whip", "Razor Leaf", "Solar Beam", "Leech Seed"],
    "Alakazam": ["Confusion", "Psychic", "Hypnosis"],
    "Machamp": ["Tackle", "Growl"],
    "Lapras": ["Water Gun", "Surf", "Ice Beam"],
    "Arcanine": ["Ember", "Flamethrower", "Fire Blast"],
    "Ivysaur": ["Tackle", "Vine Whip", "Razor Leaf", "Leech Seed"],
    "Charmeleon": ["Scratch", "Ember", "Flamethrower", "Fire Blast"],
    "Wartortle": ["Tackle", "Water Gun", "Hydro Pump", "Surf"],
    "Raichu": ["Thunder Shock", "Quick Attack", "Thunder Wave", "Thunderbolt"],
    "Sandshrew": ["Tackle", "Quick Attack", "Growl"],
    "Sandslash": ["Tackle", "Quick Attack", "Growl"],
    "Nidoran♀": ["Tackle", "Growl"],
    "Nidorina": ["Tackle", "Growl"],
    "Nidoqueen": ["Tackle", "Growl", "Hyper Beam"],
    "Nidoran♂": ["Tackle", "Growl"],
    "Nidorino": ["Tackle", "Growl"],
    "Nidoking": ["Tackle", "Growl", "Hyper Beam"],
    "Clefairy": ["Tackle", "Growl"],
    "Clefable": ["Tackle", "Growl", "Hyper Beam"],
    "Vulpix": ["Ember", "Quick Attack"],
    "Ninetales": ["Ember", "Flamethrower", "Fire Blast"],
    "Wigglytuff": ["Tackle", "Growl", "Hyper Beam"],
    "Zubat": ["Quick Attack", "Growl"],
    "Golbat": ["Quick Attack", "Growl"],
    "Oddish": ["Tackle", "Razor Leaf"],
    "Gloom": ["Tackle", "Razor Leaf"],
    "Vileplume": ["Tackle", "Razor Leaf", "Solar Beam"],
    "Paras": ["Tackle", "Razor Leaf"],
    "Parasect": ["Tackle", "Razor Leaf"],
    "Venonat": ["Tackle", "Quick Attack"],
    "Venomoth": ["Quick Attack", "Psychic"],
    "Diglett": ["Tackle", "Quick Attack"],
    "Dugtrio": ["Tackle", "Quick Attack", "Hyper Beam"],
    "Persian": ["Tackle", "Quick Attack", "Growl"],
    "Golduck": ["Water Gun", "Tackle", "Confusion", "Psychic"],
}


# All Pokemon data
pokemon_data = [
    {
        "name": "Pikachu",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/pikachu.png",
        "type_1": "Electric",
        "type_2": None,
        "hp": 35,
        "attack": 55,
        "defense": 40,
        "sp_atk": 50,
        "sp_def": 50,
        "speed": 90,
        "height": 0.4,
        "weight": 6.0,
    },
    {
        "name": "Bulbasaur",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/bulbasaur.png",
        "type_1": "Grass",
        "type_2": "Poison",
        "hp": 45,
        "attack": 49,
        "defense": 49,
        "sp_atk": 65,
        "sp_def": 65,
        "speed": 45,
        "height": 0.7,
        "weight": 6.9,
    },
    {
        "name": "Charmander",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/charmander.png",
        "type_1": "Fire",
        "type_2": None,
        "hp": 39,
        "attack": 52,
        "defense": 43,
        "sp_atk": 60,
        "sp_def": 50,
        "speed": 65,
        "height": 0.6,
        "weight": 8.5,
    },
    {
        "name": "Squirtle",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/squirtle.png",
        "type_1": "Water",
        "type_2": None,
        "hp": 44,
        "attack": 48,
        "defense": 65,
        "sp_atk": 50,
        "sp_def": 64,
        "speed": 43,
        "height": 0.5,
        "weight": 9.0,
    },
    {
        "name": "Jigglypuff",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/jigglypuff.png",
        "type_1": "Normal",
        "type_2": "Fairy",
        "hp": 115,
        "attack": 45,
        "defense": 20,
        "sp_atk": 45,
        "sp_def": 25,
        "speed": 20,
        "height": 0.5,
        "weight": 5.5,
    },
    {
        "name": "Meowth",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/meowth.png",
        "type_1": "Normal",
        "type_2": None,
        "hp": 40,
        "attack": 45,
        "defense": 35,
        "sp_atk": 40,
        "sp_def": 40,
        "speed": 90,
        "height": 0.4,
        "weight": 4.2,
    },
    {
        "name": "Psyduck",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/psyduck.png",
        "type_1": "Water",
        "type_2": None,
        "hp": 50,
        "attack": 52,
        "defense": 48,
        "sp_atk": 65,
        "sp_def": 50,
        "speed": 55,
        "height": 0.8,
        "weight": 19.6,
    },
    {
        "name": "Gengar",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/gengar.png",
        "type_1": "Ghost",
        "type_2": "Poison",
        "hp": 60,
        "attack": 65,
        "defense": 60,
        "sp_atk": 130,
        "sp_def": 75,
        "speed": 110,
        "height": 1.5,
        "weight": 40.5,
    },
    {
        "name": "Eevee",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/eevee.png",
        "type_1": "Normal",
        "type_2": None,
        "hp": 55,
        "attack": 55,
        "defense": 50,
        "sp_atk": 45,
        "sp_def": 65,
        "speed": 55,
        "height": 0.3,
        "weight": 6.5,
    },
    {
        "name": "Snorlax",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/snorlax.png",
        "type_1": "Normal",
        "type_2": None,
        "hp": 160,
        "attack": 110,
        "defense": 65,
        "sp_atk": 65,
        "sp_def": 110,
        "speed": 30,
        "height": 2.1,
        "weight": 460.0,
    },
    {
        "name": "Mewtwo",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/mewtwo.png",
        "type_1": "Psychic",
        "type_2": None,
        "hp": 106,
        "attack": 110,
        "defense": 90,
        "sp_atk": 154,
        "sp_def": 90,
        "speed": 130,
        "height": 2.0,
        "weight": 122.0,
    },
    {
        "name": "Gyarados",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/gyarados.png",
        "type_1": "Water",
        "type_2": "Flying",
        "hp": 95,
        "attack": 125,
        "defense": 79,
        "sp_atk": 60,
        "sp_def": 100,
        "speed": 81,
        "height": 6.5,
        "weight": 235.0,
    },
    {
        "name": "Dragonite",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/dragonite.png",
        "type_1": "Dragon",
        "type_2": "Flying",
        "hp": 91,
        "attack": 134,
        "defense": 95,
        "sp_atk": 100,
        "sp_def": 100,
        "speed": 80,
        "height": 2.2,
        "weight": 210.0,
    },
    {
        "name": "Charizard",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/charizard.png",
        "type_1": "Fire",
        "type_2": "Flying",
        "hp": 78,
        "attack": 84,
        "defense": 78,
        "sp_atk": 109,
        "sp_def": 85,
        "speed": 100,
        "height": 1.7,
        "weight": 90.5,
    },
    {
        "name": "Blastoise",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/blastoise.png",
        "type_1": "Water",
        "type_2": None,
        "hp": 79,
        "attack": 83,
        "defense": 100,
        "sp_atk": 85,
        "sp_def": 105,
        "speed": 78,
        "height": 1.6,
        "weight": 85.5,
    },
    {
        "name": "Venusaur",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/venusaur.png",
        "type_1": "Grass",
        "type_2": "Poison",
        "hp": 80,
        "attack": 82,
        "defense": 83,
        "sp_atk": 100,
        "sp_def": 100,
        "speed": 80,
        "height": 2.0,
        "weight": 100.0,
    },
    {
        "name": "Alakazam",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/alakazam.png",
        "type_1": "Psychic",
        "type_2": None,
        "hp": 55,
        "attack": 50,
        "defense": 45,
        "sp_atk": 135,
        "sp_def": 95,
        "speed": 120,
        "height": 1.5,
        "weight": 48.0,
    },
    {
        "name": "Machamp",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/machamp.png",
        "type_1": "Fighting",
        "type_2": None,
        "hp": 90,
        "attack": 130,
        "defense": 80,
        "sp_atk": 65,
        "sp_def": 85,
        "speed": 55,
        "height": 1.6,
        "weight": 130.0,
    },
    {
        "name": "Lapras",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/lapras.png",
        "type_1": "Water",
        "type_2": "Ice",
        "hp": 130,
        "attack": 85,
        "defense": 80,
        "sp_atk": 85,
        "sp_def": 95,
        "speed": 60,
        "height": 2.5,
        "weight": 220.0,
    },
    {
        "name": "Arcanine",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/arcanine.png",
        "type_1": "Fire",
        "type_2": None,
        "hp": 90,
        "attack": 110,
        "defense": 80,
        "sp_atk": 100,
        "sp_def": 80,
        "speed": 95,
        "height": 1.9,
        "weight": 155.0,
    },
    {
        "name": "Ivysaur",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/ivysaur.png",
        "type_1": "Grass",
        "type_2": "Poison",
        "hp": 60,
        "attack": 62,
        "defense": 63,
        "sp_atk": 80,
        "sp_def": 80,
        "speed": 60,
        "height": 1.0,
        "weight": 13.0,
    },
    {
        "name": "Charmeleon",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/charmeleon.png",
        "type_1": "Fire",
        "type_2": None,
        "hp": 58,
        "attack": 64,
        "defense": 58,
        "sp_atk": 80,
        "sp_def": 65,
        "speed": 80,
        "height": 1.1,
        "weight": 19.0,
    },
    {
        "name": "Wartortle",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/wartortle.png",
        "type_1": "Water",
        "type_2": None,
        "hp": 59,
        "attack": 63,
        "defense": 80,
        "sp_atk": 65,
        "sp_def": 80,
        "speed": 58,
        "height": 1.0,
        "weight": 22.5,
    },
    {
        "name": "Raichu",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/raichu.png",
        "type_1": "Electric",
        "type_2": None,
        "hp": 60,
        "attack": 90,
        "defense": 55,
        "sp_atk": 90,
        "sp_def": 80,
        "speed": 110,
        "height": 0.8,
        "weight": 30.0,
    },
    {
        "name": "Pikachu",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/pikachu.png",
        "type_1": "Electric",
        "type_2": None,
        "hp": 35,
        "attack": 55,
        "defense": 40,
        "sp_atk": 50,
        "sp_def": 50,
        "speed": 90,
        "height": 0.4,
        "weight": 6.0,
    },
    {
        "name": "Scizor",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/scizor.png",
        "type_1": "Bug",
        "type_2": "Steel",
        "hp": 70,
        "attack": 130,
        "defense": 100,
        "sp_atk": 55,
        "sp_def": 80,
        "speed": 65,
        "height": 1.8,
        "weight": 118.0,
    },
    {
        "name": "Togepi",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/togepi.png",
        "type_1": "Fairy",
        "type_2": None,
        "hp": 35,
        "attack": 20,
        "defense": 65,
        "sp_atk": 40,
        "sp_def": 65,
        "speed": 20,
        "height": 0.3,
        "weight": 1.5,
    },
    {
        "name": "Houndoom",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/houndoom.png",
        "type_1": "Dark",
        "type_2": "Fire",
        "hp": 75,
        "attack": 90,
        "defense": 50,
        "sp_atk": 110,
        "sp_def": 80,
        "speed": 95,
        "height": 1.4,
        "weight": 35.0,
    },
    {
        "name": "Blissey",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/blissey.png",
        "type_1": "Normal",
        "type_2": None,
        "hp": 255,
        "attack": 10,
        "defense": 10,
        "sp_atk": 75,
        "sp_def": 135,
        "speed": 55,
        "height": 1.5,
        "weight": 46.8,
    },
    {
        "name": "Tyranitar",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/tyranitar.png",
        "type_1": "Rock",
        "type_2": "Dark",
        "hp": 100,
        "attack": 134,
        "defense": 110,
        "sp_atk": 95,
        "sp_def": 100,
        "speed": 61,
        "height": 2.0,
        "weight": 202.0,
    },
    {
        "name": "Lugia",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/lugia.png",
        "type_1": "Psychic",
        "type_2": "Flying",
        "hp": 106,
        "attack": 90,
        "defense": 130,
        "sp_atk": 90,
        "sp_def": 154,
        "speed": 110,
        "height": 5.2,
        "weight": 216.0,
    },
    {
        "name": "Ho-Oh",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/ho-oh.png",
        "type_1": "Fire",
        "type_2": "Flying",
        "hp": 106,
        "attack": 130,
        "defense": 90,
        "sp_atk": 110,
        "sp_def": 154,
        "speed": 90,
        "height": 3.8,
        "weight": 199.0,
    },
    {
        "name": "Butterfree",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/butterfree.png",
        "type_1": "Bug",
        "type_2": "Flying",
        "hp": 60,
        "attack": 45,
        "defense": 50,
        "sp_atk": 90,
        "sp_def": 80,
        "speed": 70,
        "height": 1.1,
        "weight": 32.0,
    },
    {
        "name": "Beedrill",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/beedrill.png",
        "type_1": "Bug",
        "type_2": "Poison",
        "hp": 65,
        "attack": 90,
        "defense": 40,
        "sp_atk": 45,
        "sp_def": 80,
        "speed": 75,
        "height": 1.0,
        "weight": 29.5,
    },
    {
        "name": "Pidgey",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/pidgey.png",
        "type_1": "Normal",
        "type_2": "Flying",
        "hp": 40,
        "attack": 45,
        "defense": 40,
        "sp_atk": 35,
        "sp_def": 35,
        "speed": 56,
        "height": 0.3,
        "weight": 1.8,
    },
    {
        "name": "Pidgeotto",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/pidgeotto.png",
        "type_1": "Normal",
        "type_2": "Flying",
        "hp": 63,
        "attack": 60,
        "defense": 55,
        "sp_atk": 50,
        "sp_def": 50,
        "speed": 71,
        "height": 1.1,
        "weight": 30.0,
    },
    {
        "name": "Pidgeot",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/pidgeot.png",
        "type_1": "Normal",
        "type_2": "Flying",
        "hp": 83,
        "attack": 80,
        "defense": 75,
        "sp_atk": 70,
        "sp_def": 70,
        "speed": 101,
        "height": 1.5,
        "weight": 39.5,
    },
    {
        "name": "Rattata",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/rattata.png",
        "type_1": "Normal",
        "type_2": None,
        "hp": 30,
        "attack": 56,
        "defense": 35,
        "sp_atk": 25,
        "sp_def": 35,
        "speed": 72,
        "height": 0.3,
        "weight": 3.5,
    },
    {
        "name": "Raticate",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/raticate.png",
        "type_1": "Normal",
        "type_2": None,
        "hp": 55,
        "attack": 81,
        "defense": 60,
        "sp_atk": 50,
        "sp_def": 70,
        "speed": 97,
        "height": 0.7,
        "weight": 18.5,
    },
    {
        "name": "Spearow",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/spearow.png",
        "type_1": "Normal",
        "type_2": "Flying",
        "hp": 40,
        "attack": 60,
        "defense": 30,
        "sp_atk": 31,
        "sp_def": 31,
        "speed": 70,
        "height": 0.3,
        "weight": 2.0,
    },
    {
        "name": "Fearow",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/fearow.png",
        "type_1": "Normal",
        "type_2": "Flying",
        "hp": 65,
        "attack": 90,
        "defense": 65,
        "sp_atk": 61,
        "sp_def": 61,
        "speed": 100,
        "height": 1.2,
        "weight": 38.0,
    },
    {
        "name": "Ekans",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/ekans.png",
        "type_1": "Poison",
        "type_2": None,
        "hp": 35,
        "attack": 60,
        "defense": 44,
        "sp_atk": 40,
        "sp_def": 54,
        "speed": 55,
        "height": 2.0,
        "weight": 6.9,
    },
    {
        "name": "Arbok",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/arbok.png",
        "type_1": "Poison",
        "type_2": None,
        "hp": 60,
        "attack": 85,
        "defense": 69,
        "sp_atk": 65,
        "sp_def": 79,
        "speed": 80,
        "height": 3.5,
        "weight": 65.0,
    },
    {
        "name": "Sandshrew",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/sandshrew.png",
        "type_1": "Ground",
        "type_2": None,
        "hp": 50,
        "attack": 75,
        "defense": 85,
        "sp_atk": 20,
        "sp_def": 30,
        "speed": 40,
        "height": 0.6,
        "weight": 12.0,
    },
    {
        "name": "Sandslash",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/sandslash.png",
        "type_1": "Ground",
        "type_2": None,
        "hp": 75,
        "attack": 100,
        "defense": 110,
        "sp_atk": 45,
        "sp_def": 55,
        "speed": 65,
        "height": 1.0,
        "weight": 29.5,
    },
    {
        "name": "Nidoran♀",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/nidoran-f.png",
        "type_1": "Poison",
        "type_2": None,
        "hp": 55,
        "attack": 47,
        "defense": 52,
        "sp_atk": 40,
        "sp_def": 40,
        "speed": 41,
        "height": 0.4,
        "weight": 7.0,
    },
    {
        "name": "Nidorina",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/nidorina.png",
        "type_1": "Poison",
        "type_2": None,
        "hp": 70,
        "attack": 62,
        "defense": 67,
        "sp_atk": 55,
        "sp_def": 55,
        "speed": 56,
        "height": 0.8,
        "weight": 20.0,
    },
    {
        "name": "Nidoqueen",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/nidoqueen.png",
        "type_1": "Poison",
        "type_2": "Ground",
        "hp": 90,
        "attack": 92,
        "defense": 87,
        "sp_atk": 75,
        "sp_def": 85,
        "speed": 76,
        "height": 1.3,
        "weight": 60.0,
    },
    {
        "name": "Nidoran♂",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/nidoran-m.png",
        "type_1": "Poison",
        "type_2": None,
        "hp": 46,
        "attack": 57,
        "defense": 40,
        "sp_atk": 40,
        "sp_def": 40,
        "speed": 50,
        "height": 0.5,
        "weight": 9.0,
    },
    {
        "name": "Nidorino",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/nidorino.png",
        "type_1": "Poison",
        "type_2": None,
        "hp": 61,
        "attack": 72,
        "defense": 57,
        "sp_atk": 55,
        "sp_def": 55,
        "speed": 65,
        "height": 0.9,
        "weight": 19.5,
    },
    {
        "name": "Nidoking",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/nidoking.png",
        "type_1": "Poison",
        "type_2": "Ground",
        "hp": 81,
        "attack": 102,
        "defense": 77,
        "sp_atk": 85,
        "sp_def": 75,
        "speed": 85,
        "height": 1.4,
        "weight": 62.0,
    },
    {
        "name": "Clefairy",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/clefairy.png",
        "type_1": "Fairy",
        "type_2": None,
        "hp": 70,
        "attack": 45,
        "defense": 48,
        "sp_atk": 60,
        "sp_def": 65,
        "speed": 35,
        "height": 0.6,
        "weight": 7.5,
    },
    {
        "name": "Clefable",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/clefable.png",
        "type_1": "Fairy",
        "type_2": None,
        "hp": 95,
        "attack": 70,
        "defense": 73,
        "sp_atk": 95,
        "sp_def": 90,
        "speed": 60,
        "height": 1.3,
        "weight": 40.0,
    },
    {
        "name": "Vulpix",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/vulpix.png",
        "type_1": "Fire",
        "type_2": None,
        "hp": 38,
        "attack": 41,
        "defense": 40,
        "sp_atk": 50,
        "sp_def": 65,
        "speed": 65,
        "height": 0.6,
        "weight": 9.9,
    },
    {
        "name": "Ninetales",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/ninetales.png",
        "type_1": "Fire",
        "type_2": None,
        "hp": 73,
        "attack": 76,
        "defense": 75,
        "sp_atk": 81,
        "sp_def": 100,
        "speed": 100,
        "height": 1.1,
        "weight": 19.9,
    },
    {
        "name": "Jigglypuff",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/jigglypuff.png",
        "type_1": "Normal",
        "type_2": "Fairy",
        "hp": 115,
        "attack": 45,
        "defense": 20,
        "sp_atk": 45,
        "sp_def": 25,
        "speed": 20,
        "height": 0.5,
        "weight": 5.5,
    },
    {
        "name": "Wigglytuff",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/wigglytuff.png",
        "type_1": "Normal",
        "type_2": "Fairy",
        "hp": 140,
        "attack": 70,
        "defense": 45,
        "sp_atk": 85,
        "sp_def": 50,
        "speed": 45,
        "height": 1.0,
        "weight": 12.0,
    },
    {
        "name": "Zubat",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/zubat.png",
        "type_1": "Poison",
        "type_2": "Flying",
        "hp": 40,
        "attack": 45,
        "defense": 35,
        "sp_atk": 30,
        "sp_def": 40,
        "speed": 55,
        "height": 0.8,
        "weight": 7.5,
    },
    {
        "name": "Golbat",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/golbat.png",
        "type_1": "Poison",
        "type_2": "Flying",
        "hp": 75,
        "attack": 80,
        "defense": 70,
        "sp_atk": 65,
        "sp_def": 75,
        "speed": 90,
        "height": 1.6,
        "weight": 55.0,
    },
    {
        "name": "Oddish",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/oddish.png",
        "type_1": "Grass",
        "type_2": "Poison",
        "hp": 45,
        "attack": 50,
        "defense": 55,
        "sp_atk": 75,
        "sp_def": 65,
        "speed": 30,
        "height": 0.5,
        "weight": 5.4,
    },
    {
        "name": "Gloom",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/gloom.png",
        "type_1": "Grass",
        "type_2": "Poison",
        "hp": 60,
        "attack": 65,
        "defense": 70,
        "sp_atk": 85,
        "sp_def": 75,
        "speed": 40,
        "height": 0.8,
        "weight": 8.6,
    },
    {
        "name": "Vileplume",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/vileplume.png",
        "type_1": "Grass",
        "type_2": "Poison",
        "hp": 75,
        "attack": 80,
        "defense": 85,
        "sp_atk": 110,
        "sp_def": 90,
        "speed": 50,
        "height": 1.2,
        "weight": 18.6,
    },
    {
        "name": "Paras",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/paras.png",
        "type_1": "Bug",
        "type_2": "Grass",
        "hp": 35,
        "attack": 70,
        "defense": 55,
        "sp_atk": 45,
        "sp_def": 55,
        "speed": 25,
        "height": 0.3,
        "weight": 5.4,
    },
    {
        "name": "Parasect",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/parasect.png",
        "type_1": "Bug",
        "type_2": "Grass",
        "hp": 60,
        "attack": 95,
        "defense": 80,
        "sp_atk": 60,
        "sp_def": 80,
        "speed": 30,
        "height": 1.0,
        "weight": 29.5,
    },
    {
        "name": "Venonat",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/venonat.png",
        "type_1": "Bug",
        "type_2": "Poison",
        "hp": 60,
        "attack": 55,
        "defense": 50,
        "sp_atk": 40,
        "sp_def": 55,
        "speed": 45,
        "height": 1.0,
        "weight": 30.0,
    },
    {
        "name": "Venomoth",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/venomoth.png",
        "type_1": "Bug",
        "type_2": "Poison",
        "hp": 70,
        "attack": 65,
        "defense": 60,
        "sp_atk": 90,
        "sp_def": 75,
        "speed": 90,
        "height": 1.5,
        "weight": 12.5,
    },
    {
        "name": "Diglett",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/diglett.png",
        "type_1": "Ground",
        "type_2": None,
        "hp": 10,
        "attack": 55,
        "defense": 25,
        "sp_atk": 35,
        "sp_def": 45,
        "speed": 95,
        "height": 0.2,
        "weight": 0.8,
    },
    {
        "name": "Dugtrio",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/dugtrio.png",
        "type_1": "Ground",
        "type_2": None,
        "hp": 35,
        "attack": 80,
        "defense": 50,
        "sp_atk": 50,
        "sp_def": 70,
        "speed": 120,
        "height": 0.7,
        "weight": 33.3,
    },
    {
        "name": "Meowth",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/meowth.png",
        "type_1": "Normal",
        "type_2": None,
        "hp": 40,
        "attack": 45,
        "defense": 35,
        "sp_atk": 40,
        "sp_def": 40,
        "speed": 90,
        "height": 0.4,
        "weight": 4.2,
    },
    {
        "name": "Persian",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/persian.png",
        "type_1": "Normal",
        "type_2": None,
        "hp": 65,
        "attack": 70,
        "defense": 60,
        "sp_atk": 65,
        "sp_def": 65,
        "speed": 115,
        "height": 1.0,
        "weight": 32.0,
    },
    {
        "name": "Psyduck",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/psyduck.png",
        "type_1": "Water",
        "type_2": None,
        "hp": 50,
        "attack": 52,
        "defense": 48,
        "sp_atk": 65,
        "sp_def": 50,
        "speed": 55,
        "height": 0.8,
        "weight": 19.6,
    },
    {
        "name": "Golduck",
        "sprite": "https://img.pokemondb.net/sprites/sword-shield/icon/golduck.png",
        "type_1": "Water",
        "type_2": None,
        "hp": 80,
        "attack": 82,
        "defense": 78,
        "sp_atk": 95,
        "sp_def": 80,
        "speed": 85,
        "height": 1.7,
        "weight": 76.6,
    },
]